### PR TITLE
Adding XM HI3518EV300 50H20L

### PR DESCRIPTION
**Pull request by dirandad**

### CODE REVIEW

**Comment by themactep** [comment]
please use [markdown footnotes](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#footnotes) to refer to additional information

```
blahblah[^1]
foobar[^2]
...

[^1]: this and that
[^2]: that and this
```

**Comment by dirandad** [comment]
Done, but don't seem to be shown as expected

**Comment by themactep** [comment]
Do not omit colons after closing square brackets in footnotes. These are important. And you can keep footnotes lines together, no need for blank lines between them.

**Comment by dirandad** [comment]
it should be ok  now.

**Comment by themactep** [comment]
Perfect. Thank you.

**Pull request merged**
