### PR TITLE
Update sigmastar-unbrick.md

### PR DESCRIPTION
**Pull request by mixatronik**

### CODE REVIEW

**Comment by viktorxda** [comment]
You don't the CH341A, this is built into snander itself now.

**Review by viktorxda — CHANGES_REQUESTED** [review]
You don't need the CH341A kernel modules anymore, this is built into snander itself now.

**Comment by FlyRouter** [comment]
Only @viktorxda decides on approval or need for corrections

**Comment by viktorxda** [comment]
Like previously mentioned, this is no longer needed. snander itself can now access the CH341A I2C.

**Comment by mixatronik** [comment]
But without modules there is no i2c device. Or am I doing something wrong?

**Comment by viktorxda** [comment]
See here: [snander-mstar/ch341a_i2c.c](https://github.com/viktorxda/snander-mstar/blob/master/src/ch341a_i2c.c)
This was previously being handled by the external CH341A modules.

**Pull request closed without merging**
