### PR TITLE
ADD pin out 

### PR DESCRIPTION
**Pull request by lucasdellasantina**
Add pin out seual UART T31 rebranding of waze pan v3

### CODE REVIEW

**Comment by FlyRouter** [comment]
@themactep @gtxaspec 
Colleagues, please look at this PR for Ingenic and accept it or give recommendations for corrections.
Thank you.

**Comment by gtxaspec** [comment]
@lucasdellasantina do you mind cropping the photos, remove the white border?

**Review by FlyRouter — APPROVED** [review]
Thank you

**Comment by lucasdellasantina** [comment]
> @lucasdellasantina do you mind cropping the photos, remove the white border?
  
I don't see it  the white border, Could you show me where they are  border,  I can correct it?
 
image

**Pull request merged**
